
include: "rules/common.smk"
include: "rules/phylogenies.smk"
include: "rules/bacterial_contigs.smk"


rule all:
    input:
        expand([
                #"results/2_trees/{cl}/{cl}_trimmed.treefile",
                "results/2_trees/{cl}_trimmed.nw",
                #"results/4_prophages/{cl}/final-viral-boundary.tsv",
                "results/3_bacterial/{cl}.ipg",
                "results/3_bacterial/{cl}.fasta",
                "results/3_bacterial/{cl}.todownl",
                #"results/4_prophages/{cl}_bacterial.table",
                #"results/4_prophages/cl_s_550_ncbi_bacterial.table"
                ],
                cl=CLUSTERS),
